#### Install python packages

In [16]:
!pip install scdata
!pip install pandas numpy

Looking in indexes: https://pypi.org/simple/
Requirement already satisfied: pandas in ./lib/python3.10/site-packages (2.2.3)
Requirement already satisfied: numpy in ./lib/python3.10/site-packages (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./lib/python3.10/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in ./lib/python3.10/site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in ./lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [17]:
from pathlib import Path
import pandas as pd

ROOT = Path.cwd().resolve()
if ROOT.name == "src":
    ROOT = ROOT.parent
OUTPUTS = ROOT / "outputs"
CSV_DIR = OUTPUTS / "csv_files"

In [18]:
file_path = str(CSV_DIR / "places.csv")
try:
    places_df = pd.read_csv(file_path)
    print("CSV file loaded successfully!")
except FileNotFoundError:
    print(f"Error: The file '{file_path}' was not found. Please check the file path.")

CSV file loaded successfully!

In [19]:
places_df.head()

,Id,unique_id,location_type,tree_privacy,tree_height,geometry_x,geometry_y,dataset_id,dataset_name,url,submitter_name,submitter_id,submitter_user
0,37435,NaN,completed,NaN,13.47,-6.232437,53.308291,306,Richview Newstead Site,https://interval.cartospot.com/map/richview-ne...,INTERVAL Project,51.0,INTERVAL Team
1,37437,NaN,completed,NaN,9.86,-6.232577,53.308371,306,Richview Newstead Site,https://interval.cartospot.com/map/richview-ne...,INTERVAL Project,51.0,INTERVAL Team
2,37392,NaN,completed,NaN,3.41,-6.232613,53.308284,306,Richview Newstead Site,https://interval.cartospot.com/map/richview-ne...,INTERVAL Project,51.0,INTERVAL Team
3,37420,NaN,completed,NaN,10.88,-6.232427,53.308404,306,Richview Newstead Site,https://interval.cartospot.com/map/richview-ne...,INTERVAL Project,51.0,INTERVAL Team
4,37391,NaN,completed,NaN,7.67,-6.232639,53.308169,306,Richview Newstead Site,https://interval.cartospot.com/map/richview-ne...,INTERVAL Project,51.0,INTERVAL Team

In [20]:
columns_to_keep = ['Id', 'location_type', 'tree_height', 'geometry_x', 'geometry_y', 'dataset_name', 'url']
filtered_df = places_df[columns_to_keep]

In [21]:
filtered_df.head()

,Id,location_type,tree_height,geometry_x,geometry_y,dataset_name,url
0,37435,completed,13.47,-6.232437,53.308291,Richview Newstead Site,https://interval.cartospot.com/map/richview-ne...
1,37437,completed,9.86,-6.232577,53.308371,Richview Newstead Site,https://interval.cartospot.com/map/richview-ne...
2,37392,completed,3.41,-6.232613,53.308284,Richview Newstead Site,https://interval.cartospot.com/map/richview-ne...
3,37420,completed,10.88,-6.232427,53.308404,Richview Newstead Site,https://interval.cartospot.com/map/richview-ne...
4,37391,completed,7.67,-6.232639,53.308169,Richview Newstead Site,https://interval.cartospot.com/map/richview-ne...

In [22]:
submissions_file_path = str(CSV_DIR / "submissions.csv")
try:
    submissions_df = pd.read_csv(submissions_file_path)
    print("Submissions CSV file loaded successfully!")
except FileNotFoundError:
    print(f"Error: The file '{submissions_file_path}' was not found. Please check the file path.")

Submissions CSV file loaded successfully!

In [23]:
submissions_df.head()

,Id,location_id,location_unique_id,does_a_tree_exist_here,species,other_species,health,circumference,dbh,notes,image_url,submitter_name,submitter_id,submitter_user
0,37681,37435,NaN,Yes,European Beech,NaN,Good,106,33.741,Some leaves have black spots,https://community-georeports.fra1.cdn.digitalo...,Aoife O'Dwyer,NaN,NaN
1,37675,37437,NaN,Yes,Elm,NaN,Fair,0,0.000,Can’t access the tree,https://community-georeports.fra1.cdn.digitalo...,NaN,NaN,NaN
2,37672,37392,NaN,Yes,Black Walnut,NaN,Fair,40,12.732,Covered base in ivy completely,https://community-georeports.fra1.cdn.digitalo...,NaN,NaN,NaN
3,37669,37420,NaN,Yes,Willow,NaN,Poor,38,12.096,Grey willow - dead,https://community-georeports.fra1.cdn.digitalo...,NaN,NaN,NaN
4,37667,37391,NaN,Yes,Common Hazel,NaN,Good,0,0.000,Trunk covered in ivy,https://community-georeports.fra1.cdn.digitalo...,NaN,NaN,NaN

In [24]:
merged_df = pd.merge(
    filtered_df,  # The places DataFrame
    submissions_df,  # The submissions DataFrame
    left_on='Id',  # Column in filtered_df
    right_on='location_id',  # Column in submissions_df
    how='inner'  # Join type: only matching rows will be kept
)

In [25]:
merged_df.head()

,Id_x,location_type,tree_height,geometry_x,geometry_y,dataset_name,url,Id_y,location_id,location_unique_id,...,species,other_species,health,circumference,dbh,notes,image_url,submitter_name,submitter_id,submitter_user
0,37435,completed,13.47,-6.232437,53.308291,Richview Newstead Site,https://interval.cartospot.com/map/richview-ne...,37681,37435,NaN,...,European Beech,NaN,Good,106,33.741,Some leaves have black spots,https://community-georeports.fra1.cdn.digitalo...,Aoife O'Dwyer,NaN,NaN
1,37437,completed,9.86,-6.232577,53.308371,Richview Newstead Site,https://interval.cartospot.com/map/richview-ne...,37675,37437,NaN,...,Elm,NaN,Fair,0,0.000,Can’t access the tree,https://community-georeports.fra1.cdn.digitalo...,NaN,NaN,NaN
2,37392,completed,3.41,-6.232613,53.308284,Richview Newstead Site,https://interval.cartospot.com/map/richview-ne...,37672,37392,NaN,...,Black Walnut,NaN,Fair,40,12.732,Covered base in ivy completely,https://community-georeports.fra1.cdn.digitalo...,NaN,NaN,NaN
3,37420,completed,10.88,-6.232427,53.308404,Richview Newstead Site,https://interval.cartospot.com/map/richview-ne...,37669,37420,NaN,...,Willow,NaN,Poor,38,12.096,Grey willow - dead,https://community-georeports.fra1.cdn.digitalo...,NaN,NaN,NaN
4,37391,completed,7.67,-6.232639,53.308169,Richview Newstead Site,https://interval.cartospot.com/map/richview-ne...,37667,37391,NaN,...,Common Hazel,NaN,Good,0,0.000,Trunk covered in ivy,https://community-georeports.fra1.cdn.digitalo...,NaN,NaN,NaN

In [26]:
# Step 12: Count the number of submissions per place (Id_x)
submission_counts = merged_df.groupby('Id_x').size().reset_index(name='submission_count')

# Step 13: Merge the counts back to the merged_df to associate each place with its count
merged_with_counts = pd.merge(merged_df, submission_counts, on='Id_x')

# Step 14: Filter places with only one submission
single_submission_df = merged_with_counts[merged_with_counts['submission_count'] == 1]

# Step 15: Filter places with multiple submissions
multiple_submissions_df = merged_with_counts[merged_with_counts['submission_count'] > 1]

# Step 16: Export the filtered DataFrames to separate CSV files
CSV_DIR.mkdir(parents=True, exist_ok=True)
single_submission_file = str(CSV_DIR / "places_with_single_submission.csv")
multiple_submissions_file = str(CSV_DIR / "places_with_multiple_submissions.csv")

try:
    # Export single submissions
    single_submission_df.to_csv(single_submission_file, index=False)
    print(f"Single submission DataFrame exported to '{single_submission_file}' with {single_submission_df.shape[0]} rows.")
    
    # Export multiple submissions
    multiple_submissions_df.to_csv(multiple_submissions_file, index=False)
    print(f"Multiple submissions DataFrame exported to '{multiple_submissions_file}' with {multiple_submissions_df.shape[0]} rows.")
except Exception as e:
    print(f"Error exporting files: {e}")

Single submission DataFrame exported to 'places_with_single_submission.csv' with 37 rows.
Multiple submissions DataFrame exported to 'places_with_multiple_submissions.csv' with 8 rows.